#!/bin/bash
# Use find to list all directories (including the current directory)
# and pass the output to the wc command to count the number of lines
num_dirs=$(find . -type d | wc -l)
# Subtract 1 from the count to exclude the current directory itself
num_dirs=$((num_dirs - 1))
echo "Number of directories and sub-directories in the current directory: $num_dirs"
